sudo: required

dist: trusty

language: node_js

node_js:
  - "6"
  - "8"
  - "10"

script: npm run test:coveralls

after_success:
  - npm run coveralls

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
