language: java

env:
  - NODE_VERSION=0.10
  - NODE_VERSION=0.12
  - NODE_VERSION=iojs

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
  - nvm install "$NODE_VERSION"

install:
  - npm install -g grunt-cli
  - npm install

script:
  - npm test

matrix:
  fast_finish: true
