name: Tests
on: [push, pull_request]

jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [8.16.1, 10, 12]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version
      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coveralls

      - name: Run Coveralls
        run: npm run coveralls
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == 10 && github.repository == 'validator/grunt-html' && github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
